baseURL = 'https://stephen.period-domain.com/'
locale = 'en-us'
hasCJKLanguage = true
title = "Stephen’s period domain"
theme = 'HugoTeX'
enableInlineShortcodes = true
foornoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[Params.author]
  name = "Stephen Liu"
  first_name = "Stephen"
  middle_name = "Sicheng"
  last_name = "Liu"
  name_alt = "劉思承"
  abstract = """
  I'm a third year PhD student in the department of mathematics at Temple University, advised by Matthew Stover. My current interest lies in the intersection between geometric topology and complex algebraic geometry. 
  """
  email = "sicheng.liu@temple.edu"

# [markup.highlight]
#   style = 'dracula'

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params.Favicon]
#   ico = "/favicon.ico"                     # Legacy multi-size .ico fallback
#   svg = "/favicon.svg"                     # SVG icon for modern browsers
  png = "/favicon.png"                     # 180x180 PNG fallback and Apple touch icon

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['$', '$'], ['\(', '\)']]
          block  = [['$$', '$$'], ['\[', '\]']]
  [markup.highlight]
    style = "paraiso-dark"

[refLinks]
notFoundURLs = "warning"
