baseURL = 'https://sl.period-domain.com/'
locale = 'en-us'
title = 'Stephen Liu'
theme = 'HugoTeX'
enableInlineShortcodes = true
foornoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[Params.author]
  name = "Stephen Liu"
  abstract = """
  Hey
  """

# [markup.highlight]
#   style = 'dracula'

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params.Favicon]
#   ico = "/favicon.ico"                     # Legacy multi-size .ico fallback
#   svg = "/favicon.svg"                     # SVG icon for modern browsers
  png = "/favicon.png"                     # 180x180 PNG fallback and Apple touch icon

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['$', '$']]
          block = [['$$', '$$']]
  [markup.highlight]
    style = "paraiso-dark"
