baseURL = 'https://sl.period-domain.com/'
locale = 'en-us'
title = 'SCX'
theme = 'HugoTeX'
enableInlineShortcodes = true
foornoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[Params.author]
  name = "SCX"
  abstract = """
  Hey
  """

[markup.highlight]
  style = 'dracula'

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'